### ISSUE TITLE
Not useful for Software Engineers

### ISSUE THREAD

**Issue by safinghoghabori** [liantze/AltaCV#100]
I'm quite impressed with this resume. But unfortunately, it can't be used as SDE's resume. Can you create one for the same? i.e. covering the following sections projects, achievements, skills etc (without any profile pic or image)

**Comment by liantze** [comment]
AltaCV only provides the _layout and style definitions_ that may be useful for a CV or résumé. It has never been the aim to provide a "sample CV" with "useful sections" for job-seekers from different fields or backgrounds. Therefore this is irrelevant to AltaCV; it would be much better to seek advice from career advisory services.
