### ISSUE TITLE
Cannot use footer

### ISSUE THREAD

**Issue by JiaxinZhong** [liantze/AltaCV#101]
Hi everyone,

I want to add a footer using the following codes, but the footer is not shown. Could you please help me with this issue? Thanks!

```
\usepackage{lastpage}
\usepackage{fancyhdr}
\fancyhf{} % clear existing header/footer entries
% Place Page X of Y on the right-hand
% side of the footer
\fancyfoot[R]{Page \thepage \hspace{1pt} of \pageref{LastPage}}
```

**Comment by liantze** [comment]
You may need to adjust your `\geometry` parameters, especially `footskip`. See #33
