### ISSUE TITLE
How do I control the font sizes?

### ISSUE THREAD

**Issue by subhaminion** [liantze/AltaCV#103]

**Comment by NicolasOmar** [comment]
I think you can check on [mmayer.tex, lines from 54 to 57](https://github.com/liantze/AltaCV/blob/483e6a60e218589cef65cab5e760e69f2718eacd/mmayer.tex#L53), there are mentions of font sizes.

**Comment by liantze** [comment]
`altacv.cls` uses `extarticle`. If you just want to make all the text in the document larger, change `10pt` in the `\documentclass` options  to a suitable size supported by `extarticle`: The sizes available are 8pt, 9pt, 10pt, 11pt, 12pt, 14pt, 17pt, and 20pt. See also https://texdoc.org/pkg/extsizes, section 3.

If you want to change the font size of specific elements, look for the line `% Change some fonts, if necessary` in mmayer.tex or sample.tex, and edit the lines as necessary.

**Comment by aliraeisdanaei** [comment]
I had a lot of trouble setting the font by the ``\documentclass``.it seems that changing the line ``\LoadClass{article}`` to ``\LoadClass{extarticle}`` completely solved my problem.
