### ISSUE TITLE
Use `alt` Fontawesome for `faCalendar` and `faMapMarker`

### ISSUE THREAD

**Issue by dmohns** [liantze/AltaCV#109]
The calendar and location icons used in a `cvevent` currently look a bit odd, and not quite like the original design. 

Simply replace `\faMapMarker` with `\faMapMarker*`. For the calendar icon I (personally) would even consider using the _regular_ version of the icon (which is luckily part of free), i.e. `\faCalendar*[regular]`.

Before:
<img width="355" alt="image" src="https://github.com/liantze/AltaCV/assets/14202480/3934d010-35ed-4157-88b4-65a5d05f725c">

After:
<img width="320" alt="image" src="https://github.com/liantze/AltaCV/assets/14202480/8e4e57bd-1932-4537-a559-ad0546f3f568">

Note: The MapMarker icon should also be changed in the header.

**Comment by liantze** [comment]
You can change these using `\patchcmd` to replace these `fontawesome5` symbols in the `\cvevent` definition, by adding these lines before `\begin{document}`:

```latex
\patchcmd{\cvevent}{\faCalendar}{\faCalendar*[regular]}{}{}
\patchcmd{\cvevent}{\faMapMarker}{\faMapMarker*}{}{}
```

So if you had preferred to use coloured emojis you could even do

```latex
\usepackage{emoji} % Requires LuaLaTeX as compiler
\patchcmd{\cvevent}{\faCalendar}{\emoji{calendar}}{}{}
\patchcmd{\cvevent}{\faMapMarker}{\emoji{world-map}}{}{}
```

(It's probably easier if these are placed into macros e.g. with current `\itemmarker`, `\ratingmarker`. Something for a future version.)

**Comment by dmohns** [comment]
Cool, thanks, I made it work for my setup. 

Should I leave this issue open as a reminder for future improvements?

**Comment by liantze** [comment]
Maybe close this one for now — the actual choice for default icons can be rather dependent on personal preferences. I'll make a personal note to implement `\cveventdatemarker` and `\cvlocationmarker`.

**Comment by liantze** [comment]
With altacv.cls v1.7 this can now be done with
```latex
\renewcommand{\cvDateMarker}{\faCalendar*[regular]}
\renewcommand{\cvLocationMarker}{\faMapMarker*}
```
