### ISSUE TITLE
\newpage command does not work

### ISSUE THREAD

**Issue by aflexa** [liantze/AltaCV#11]
The \newpage command does not work for the page1sidebar. If the text does not fit on the first page it is not transferred to the next one. Alternatively, tried to manually put it on the next page with the newpage command but it doesn't work. Any suggestions? 

Cheers

**Comment by liantze** [comment]
The sidebar can't `\clearpage`, `\newpage` nor break across pages on its own. It's really a `\marginpar`, which can't do things like that in LaTeX. So you'll have to manually move the extra sections into the file `page2sidebar.tex`.  

There is a new command `\addnextpagesidebar` as well; see comments at the end of `sample.tex` and `mmayer.tex`:

````
%% If the NEXT page doesn't start with a \cvsection but you'd
%% still like to add a sidebar, then use this command on THIS
%% page to add it. The optional argument lets you pull up the 
%% sidebar a bit so that it looks aligned with the top of the
%% main column.
% \addnextpagesidebar[-1ex]{page3sidebar}
```

**Comment by LesliekWood** [comment]
is there anyway to not show the sidebar on page 2?

**Comment by liantze** [comment]
> is there anyway to not show the sidebar on page 2?

This seems to be a duplicate of #95 (and replied there)

**Comment by sleebapaul** [comment]
@liantze I wanted to lift the sidebar in the second page. Seems like `\addnextpagesidebar[-1ex]{page2sidebar}` is not working. 

1. My second page is not starting with the `\cvsection`. 
2. So I added, a new `\cvsection[page2sidebar]{Publications}` on the second page and, the sidebar comes in the mid of the second page aligning the `Publications`. 
3. I want the side bar to go up and match the starting line of the second page (which is not a `\cvsection`)

```
The optional argument lets you pull up the 
%% sidebar a bit so that it looks aligned with the top of the
%% main column.
```
What is this optional argument?
