### ISSUE TITLE
[Question] Display header on each page of CV

### ISSUE THREAD

**Issue by dmohns** [liantze/AltaCV#110]
Updating from an ancient version of AltaCV I encountered a small issue. In earlier versions (prior to `paracol`) it was easy to display the header on each page of the CV by simply calling `\makecvheader` on each page.

With `paracol` I couldn't find a simple way to achieve the same result. Any ideas how this could be achieved?

**Comment by liantze** [comment]
If you prefer to control exactly where each page ends, you can issue an `\end{paracol}`, then add `\clearpage\makecvheader` and start the two-column layout again with another `\begin{paracol}{2}`.

Or if you prefer to use just one single `paracol` environment throughout the document and let `paracol` handle the column/page switching automatically, then consider using `\makecvheader` in a page header instead, by adding these lines before `\begin{document}`:

```latex
% Add includehead so that the "top" margin will be from the top of the page header 
% to the top edge of the paper, and specify a large enough "head" height to 
% accommodate your \makecvheader material
\geometry{left=1.25cm,right=1.25cm,top=1.5cm,includehead,head=80pt,
bottom=1.5cm,columnsep=1.2cm}

% Load the fancyhdr package
\usepackage{fancyhdr}

% put \makecvheader in the page header
\fancyhf{}\renewcommand{\headrule}{}
\fancyhead[C]{\makecvheader}

% Activate the "fancy" page style. 
% (by default altacv.cls would have set it to empty)
\AddToHook{begindocument/before}{\pagestyle{fancy}}
```

**Comment by dmohns** [comment]
> If you prefer to control exactly where each page ends, you can issue an `\end{paracol}`, then add `\clearpage\makecvheader` and start the two-column layout again with another `\begin{paracol}{2}`.

Oh, of course 😇 I'm already controlling page switching manually inside each of the columns. So, this solves it quite nicely. Thanks!
