### ISSUE TITLE
Author highlight in publication section

### ISSUE THREAD

**Issue by gVallverdu** [liantze/AltaCV#116]
Hi

I tried to use the included option that turn bold author names in `\mynames` list. But it seems it does not work. I did it on your sample.tex example.

I tried both with xelatex and pdflatex. I ran pdflated; biber; pdflatex.

Is a special compilation option needed or a minimal texlive version ?

**Comment by gVallverdu** [comment]
In case other enter in the same issue, here are some remarks:

* it does not work with TexLive 2021 but it does with TexLive 2024 (and 2023 on overleaf)
* The names you write in `\mynames` have to match what is in the bib file, whatever the bib style you are using. For example, if there is `Lim, Tracy` in the author field in the bibtex file, and the output in the bibliography is `Lim, T.`, you have to write `Lim/Tracy` in `\mynames`.

On another hand, if you want, I add the following macro to the class to include "project" without location but with the possibility to say your position/role in the project:


```latex
\newcommand{\cvRoleMarker}{\faUsers}
\newcommand{\rolename}{role}

...

\newcommand{\cvproject}[3]{%
  {\large\color{emphasis}#1}
  \normalsize
  \qquad%
  \ifstrequal{#2}{}{}{%
    {\small%
      \BeginAccSupp{method=pdfstringdef,ActualText={\datename:}}\cvDateMarker\EndAccSupp{}%
      ~#2%
    }}%
  \qquad%
  \ifstrequal{#3}{}{}{%
    {\small%
      \BeginAccSupp{method=pdfstringdef,ActualText={\rolename:}}\cvRoleMarker\EndAccSupp{}%
        ~#3%
    }}\par
  \medskip\normalsize
}
```

**Comment by liantze** [comment]
> * it does not work with TexLive 2021 but it does with TexLive 2024 (and 2023 on overleaf)

LaTeX's hooks management for packages had some syntax change: between `2020-10-01` and `2021-11-15` the syntax was `\AddToHook{package/after/<name>}`, but this was changed to `\AddToHook{package/<name>/after}` after `2021-11-15`. 
This should now be accounted for by https://github.com/liantze/AltaCV/commit/f1c41cf9b70968100e30c6a132e6e4813d3f6d33 .


> * The names you write in `\mynames` have to match what is in the bib file, whatever the bib style you are using. 

Yes indeed; see [comments just before `\mynames`](https://github.com/liantze/AltaCV/blob/f1c41cf9b70968100e30c6a132e6e4813d3f6d33/sample.tex#L196-L198) in `sample.tex`.
