### ISSUE TITLE
Change PersonalInfo Font Size

### ISSUE THREAD

**Issue by KevinFocke** [liantze/AltaCV#121]
Hello,

Not familiar with LaTeX. How can I change icon size of the personal info (third row)?

![image](https://github.com/user-attachments/assets/6493f366-7474-4511-b844-6e602f8bdd63)

I think the section is called personalinfo:
![image](https://github.com/user-attachments/assets/103d5534-88fe-42a9-8eb8-952201f3577f)

And is controlled via this command:
![image](https://github.com/user-attachments/assets/c68953d5-2654-4703-80b9-a77293d6a34f)

I expect adding the footnotesize in this way would work, but that is not the case:
![image](https://github.com/user-attachments/assets/94929be9-4b74-415f-a5a3-57d0b500dac8)

How can I change the font size of the personal info?

**Comment by liantze** [comment]
You would need to use one of the built-in commands for setting font sizes, as listed here https://en.wikibooks.org/wiki/LaTeX/Fonts#Built-in_sizes. The sample templte uses `10pt` in `\documentclass` as the document's body font size, so 12pt would be `\large` (see table in that link).

```latex
\renewcommand{\personalinfofont}{\large}
```

If you had wanted to set an arbitrary font size https://en.wikibooks.org/wiki/LaTeX/Fonts#Arbitrary_sizes then you would need

```latex
\renewcommand{\personalinfofont}{\fontsize{13pt}{16pt}\selectfont}
```
