### ISSUE TITLE
ifxetexorluatex  error

### ISSUE THREAD

**Issue by countbytedown** [liantze/AltaCV#122]
Fails to build

! Undefined control sequence.
l.32 \ifxetexorluatex

I beleive there is a PR in that fxes this

This is LuaHBTeX, Version 1.18.0 (TeX Live 2024)
Development id: 7611

**Comment by liantze** [comment]
If you change `\ifxetexorluatex` in sample.tex (or mmayer.tex) to be `\iftutex`, does it compile without errors?

**Comment by countbytedown** [comment]
Hi @liantze,
This PR has that solution
https://github.com/liantze/AltaCV/pull/120/files

I personally did this. Great work btw.
```
\ifLuaTeX\else\ifXeTeX
  % Commands for LuaLaTeX OR XeLaTeX
  \usepackage{fontspec}
  \setmainfont{Roboto Slab}
  \setsansfont{Lato}
  \renewcommand{\familydefault}{\sfdefault}
\else
  % Commands for pdfLaTeX or other engines
  \usepackage[rm]{roboto}
  \usepackage[defaultsans]{lato}
  \renewcommand{\familydefault}{\sfdefault}
\fi\fi
```

**Comment by liantze** [comment]
Thanks, but `\iftutex` should be the correct macro to use. It replaced `\ifxetexorluatex` in [`altacv.cls` v1.7.3 in f1c41cf](https://github.com/liantze/AltaCV/commit/f1c41cf9b70968100e30c6a132e6e4813d3f6d33#diff-ab4677a1b42e30d7eafa8f35af7f99a7b22a65aa22a7adb0920d0b60d7f26b99R73), but I forgot to include the modified `.tex` files with `\iftutex` in the same commit and push. 

I had even [updated it correctly on Overleaf](https://www.overleaf.com/latex/templates/altacv-template/trgqjpwnmtgv)! but not in my git commit 🤦🏻 . Just pushed cd1e96a yesterday with the correct .tex files now.

Thanks again for raising this — that really fell off my radar!

**Comment by countbytedown** [comment]
Thanks very much....everything is good
