### ISSUE TITLE
Font size of Company/University inconsistent

### ISSUE THREAD

**Issue by stefanogermano** [liantze/AltaCV#16]
The font size of the second argument ("Company") in the first element of the "Experience" section is bigger than the other (red line in the image below).
All the other arguments are consistent (blue line in the image below).

![experience](https://user-images.githubusercontent.com/2128484/43276686-d02fd888-9105-11e8-98a6-4af8dec48302.png)

This does not happen in the "Projects" section (that also uses `\cvevent`):

![projects](https://user-images.githubusercontent.com/2128484/43276700-dcb4cd34-9105-11e8-803b-c67594a72046.png)

However, it happens in the "Education" section (in the sidebar):

![education](https://user-images.githubusercontent.com/2128484/43277757-4a3e5660-9109-11e8-88e6-1e87f8897f66.png)

Is this done on purpose?

Is there a way to disable this behaviour?

**Comment by liantze** [comment]
Thanks good catch! Should now be fixed.
