### ISSUE TITLE
sidebar left position

### ISSUE THREAD

**Issue by shannonpileggi** [liantze/AltaCV#19]
How can I modify the .cls to have the sidebar in the left position instead of the right?

**Comment by liantze** [comment]
First swap the `\geometry` margins around so that you have on line 38 of the `.tex` file:
````
\geometry{left=1cm,right=9cm, ... 
````

Then add these lines:

````
\reversemarginpar
\patchcmd{\fullwidth}
  {\begin{adjustwidth}{}{\dimexpr-\marginparwidth-\marginparsep\relax}}}
  {\begin{adjustwidth}{}{\dimexpr-\marginparwidth-\marginparsep\relax}}}
````

That should do it.

**Comment by shannonpileggi** [comment]
Super, thanks!  However, when I do that the header right aligns with the sidebar on the right instead of left aligns.  How can I fix that?

**Comment by liantze** [comment]
This is what I see: 

<img width="959" alt="screen shot 2018-10-06 at 3 38 16 pm" src="https://user-images.githubusercontent.com/1103696/46568809-e7b08380-c97d-11e8-94c8-377a83aad698.png">

Are you getting a different output?
