### ISSUE TITLE
Publication list empty

### ISSUE THREAD

**Issue by WACMemphis** [liantze/AltaCV#2]
I've downloaded the repository and compiled it with Pdflatex, Lualatex and Xelatex.

Everything looks just fine except that the "Publications" section is empty. I can't make the references show up at all.

Any idea why that might be?

**Comment by sebastian-raubach** [comment]
Ok, nevermind. My bad. Didn't use Biber. Resolved now.

**Comment by WACMemphis** [comment]
Sorry, my mistake. Didn't use Biber. Resolved now.
