### ISSUE TITLE
Font type changing in altacv.cls file

### ISSUE THREAD

**Issue by KarimCB** [liantze/AltaCV#22]
I am a beginner in LATeX and I'm writing a CV choosing this template, one thing I couldn't find is the part of the code in altacv.cls file where I can change the font family/type face that I prefer over the current default font. Could you please clarify this?

**Comment by liantze** [comment]
`altacv.cls` doesn't set any font; you can change `\usepackage{lato}` in the `.tex` file's preamble instead. It's in the `.tex` on purpose to make it easier for users to switch fonts.
