### ISSUE TITLE
Compile sample-CV with LuaLaTeX - Error with academicons

### ISSUE THREAD

**Issue by Hofer-Julian** [liantze/AltaCV#23]
Hi!

When I compile the sample-CV with LuaLaTeX and change
`\documentclass[10pt,a4paper,ragged2e]{altacv}`
to
`\documentclass[10pt,a4paper,academicons]{altacv}`
I get the following error:
`LaTeX error: "xparse/command-already-defined" Command '\AI' already defined! For immediate help type H <return>. \fi`.

This error disappears when I modify the patch to make academicons compilable with XeLaTeX in `altacv.cls`

```
%% v1.1: Optionally load academicons
\if@academicons
  %% Patch to make academicons compilable with XeLaTeX
  \ExplSyntaxOn
  \msg_redirect_name:nnn { fontspec } { font-not-found } { none }
  \ExplSyntaxOff
  \RequirePackage{academicons}
  \newfontfamily{\AI}{academicons.ttf}
\fi
```

**Comment by liantze** [comment]
Thanks for reporting this. Could you let me know the version of `altacv` you're using?

**Comment by Hofer-Julian** [comment]
It is v1.1.4, 27 July 2018

**Comment by Hofer-Julian** [comment]
Your patch works perfectly!

Thank you for this and your nice CV in general :)
