### ISSUE TITLE
adding a cvsection causes a repeat in the sidebar

### ISSUE THREAD

**Issue by boryanakis** [liantze/AltaCV#27]
Hi, 

I am trying to add a "professional summary" section at the top of the first page. So, I simply added 

```
\cvsection[page1sidebar]{Professional Summary}
Here is my professional summary.
```

right before the Experience section. As soon as I do that, I see a repeat of the top section of the sidebar at the bottom of the sidebar (see attached screenshot - the star is the only change I have made from the template using the above two lines of code). Could you please advice on what I am doing wrong, or if there is a work-around? Thank you! 

PS: Even if I remove the "A Day Of My Life" section, the repeat appears. 

<img width="605" alt="altacv_screenshot" src="https://user-images.githubusercontent.com/1775273/56631261-27894080-661a-11e9-9ace-f2e773a32d25.png">

**Comment by liantze** [comment]
The `[page1sidebar]` bit is the code that inserts the sidebar sections from `page1sidebar.tex`, so you would want to check if you have two `\cvsection`s that has `[page1sidebar]`. (You probably haven't yet deleted it from the `\cvsection{Experience}` line.) 

Only one `\cvsection` should have a `[page1sidebar]` on each page.

**Comment by boryanakis** [comment]
Thank you so much! I should have noticed it. I really appreciate you getting back to me so quickly.

**Comment by liantze** [comment]
No problem! :D
