### ISSUE TITLE
e-Mail Hyperlink seems not to work

### ISSUE THREAD

**Issue by jenskr** [liantze/AltaCV#29]
When the e-Mail link in the sample pdf is clicked, I get the following e-Mail Address: 'your@email.comÓ000-00-0000RAddress' (without quotes). 

Any suggestions how to remedy this?

**Comment by liantze** [comment]
The sample PDF actually doesn't have any active hyperlinks at all.

If you want hyperlinks, including mailto links, you need to load `\usepackage{hyperref}` and do up the links yourself:

```
\email{\href{mailto:your@email.com}{your@email.com}}
```

**Comment by mishal23** [comment]
Hi @liantze 

Tried using it in Overleaf with pdflatex compiler, it gives an error: 

```
TeX capacity exceeded, sorry [input stack size=5000].
```

Any suggestions to prevent this?

**Comment by liantze** [comment]
Works fine for me with AltaCV v1.3.2 using `withhyper` document class option in pdflatex TeX Live 2019:

<img width="1386" alt="Screenshot 2020-06-04 at 3 20 07 PM" src="https://user-images.githubusercontent.com/1103696/83726950-e36acb00-a676-11ea-849f-d61d9bb5d339.png">
