### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by arafat-hasan** [liantze/AltaCV#33]
Add footer option. Page number, compile date, resume owner's name can be shown in the footer. Footer will be optional.

**Comment by T-Zema** [comment]
up ;)

**Comment by liantze** [comment]
You can do this with the `fancyhdr` package yourself:

```latex
%% add the footskip option to adjust location of footer
\geometry{left=1cm,...,footskip=1.5\baselineskip}
\usepackage{fancyhdr}
\fancyhf{}
\renewcommand{\headrule}{}
\fancyfoot[L]{\footnotesize whatever you need}
\AtBeginDocument{\pagestyle{fancy}}
```

**Comment by kemot90** [comment]
It works for me but with geometry defined like this:
```latex
\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,headheight=17pt,includefoot,heightrounded,columnsep=1.2cm}```

**Comment by scamgi** [comment]
Hey guys,

I'm a LaTex newbie, and I dunno where to put that piece of code. I tried to put it at the end of the document but it doesn't work. Can you explain where I can write it?

**Comment by Mara01010011** [comment]
@scamgi Just below the beginning `\documentclass....` you already have a `\geometry...`. Just comment that out and insert the code above.
