### ISSUE TITLE
Double photo in the Header

### ISSUE THREAD

**Issue by joaomartins-git** [liantze/AltaCV#35]
Hi! 

I was trying to put another photo in the header of the resumé but it only appears the corresponding "code", never the actual photo.

![Screenshot 2019-12-12 at 14 06 34](https://user-images.githubusercontent.com/56981836/70718899-041a1f80-1ce9-11ea-9aab-b9c2fe5e66b9.png)

I found this resumé, that someone used and altered the AltaCV, and i was trying to do it just like that. By any chance, is this possible? What can i "alter" so that mine does the same?

**Comment by joaomartins-git** [comment]
> Hi!
> 
> I was trying to put another photo in the header of the resumé but it only appears the corresponding "code", never the actual photo.
> 
> ![Screenshot 2019-12-12 at 14 06 34](https://user-images.githubusercontent.com/56981836/70718899-041a1f80-1ce9-11ea-9aab-b9c2fe5e66b9.png)
> 
> I found this resumé, that someone used and altered the AltaCV, and i was trying to do it just like that. By any chance, is this possible? What can i "alter" so that mine does the same?

The resumé that i found was written using the AltaCV template, but an old one.

**Comment by jgoliveira** [comment]
Hey, I just submitted a PR that addresses your request. #36 
Take a look.
Feel free to ask any questions

**Comment by janjur** [comment]
I would love to add my company logo to the CV :)

**Comment by jgoliveira** [comment]
> I would love to add my company logo to the CV :)

@janjur feel free to implement the changes I did on the PR #36 .
With that, you can have a profile pic on one side, and a company logo on the other :)

**Comment by liantze** [comment]
I should have an update ready in a couple of days; will just need to finish tidying up the code abit. Essentially you'll be able to do
```
\photoL{2cm}{logo1,photo1,photo2}
\photoR{2cm}{photo3,photo4}
```
assuming that there's enough space to fit them all on one row of course. :-)

**Comment by liantze** [comment]
@janjur @jgoliveira If you download `altacv.cls` v1.2, you can now use the new `\photoL` and `\photoR` commands with a comma-separated list of image filenames to add multiple photos.
