### ISSUE TITLE
Bibtex issue running exemple

### ISSUE THREAD

**Issue by clementviolet** [liantze/AltaCV#40]
Hi ! Thanks for your hard work !

I have an issue when I try to reproduce your two exemples. I can't include the references include in the `.bibtex`.

I compile the exemples with `LuaLaTeX` then `Bibtex` and I've got the following error messages.

```
This is BibTeX, Version 0.99d (TeX Live 2019)
The top-level auxiliary file: mmayer.aux
I found no \citation commands---while reading file mayor.aux
I found no \bibdata commands---while reading file mayor.aux
I found no \bibstyle commands---while reading file mayor.aux
```

I'm using `LuaTeX, Version 1.10.0`from `TeX Live 2019` on my MacBook Air.

I have no idea what the problem is... 😞

**Comment by liantze** [comment]
These samples use `biblatex` and `biber`, so instead of running `bibtex sample-alt` (or `bibtex sample`) try instead `biber sample-alt` (or `biber sample-alt`), depending on which .tex file you're using.
