### ISSUE TITLE
columns ration optimization options

### ISSUE THREAD

**Issue by salama4** [liantze/AltaCV#41]
how to change the ratio of left/right columns, \columnratio{0.5} does not work

**Comment by liantze** [comment]
This should work just fine:

<img width="939" alt="Screenshot 2020-02-25 at 10 12 55 AM" src="https://user-images.githubusercontent.com/1103696/75208703-672f3480-57b7-11ea-9123-353a8dc62c0b.png">

Are you seeing any error messages?

**Comment by liantze** [comment]
Also make sure that you're using `sample-alt.tex`, not `sample.tex`, if you want to use `\columnratio`.

(Your questions are not about "optimisation" but simply changing the options/customisations; so I've edited the issue titles.)
