### ISSUE TITLE
changing the title background color

### ISSUE THREAD

**Issue by salama4** [liantze/AltaCV#44]
i.e how to make the color background of the title only different relative to the rest of document,

**Comment by theraghul** [comment]
Hi ! i'm new to latex will you pls guide me to how to add publication details & Books Info?

**Comment by liantze** [comment]
You will need to redefine `\cvsection` yourself. Something like 
```latex
\renewcommand{\cvsection}[1]{%
  \bigskip\setlength{\fboxsep}{6pt}%
  \colorbox{heading}{\cvsectionfont\color{white}%
  \parbox{\linewidth}{#1}%
  }\par\medskip%
}
```
(Personally I don't quite like this style, as it can be visually too "heavy".)
