### ISSUE TITLE
add summary section full width

### ISSUE THREAD

**Issue by eyadsibai** [liantze/AltaCV#47]
I tried to add a summary section with full width, but the right side went over the page.
```
\begin{fullwidth}
\makecvheader

\cvsection{Summary}
xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

\end{fullwidth}```

I added this piece of code

**Comment by eyadsibai** [comment]
not sure why the full width did not respect the right margin

**Comment by liantze** [comment]
Use `sample-alt.tex` as a starting file instead: everything outside the `paracol` environment is "full width" in this template i.e. do not use `fullwidth` anywhere in `sample-alt.tex`.
