### ISSUE TITLE
Special characters won't display properly

### ISSUE THREAD

**Issue by gcakir** [liantze/AltaCV#48]
<img width="178" alt="problem" src="https://user-images.githubusercontent.com/19774563/81948794-6b266200-9602-11ea-82f9-8f0572a11a78.png">
For example, as in the image, the German letter **_"ö"_** in "Göttingen" will be displayed as **_"Ãű"_**, resulting in **_"GÃűttingen"_**. How could I resolve this issue?

**Comment by liantze** [comment]
This is a new bug with the new code attempting to automatically handle special characters like `_` with `\detokenize`. I'll look into this; in the meantime can you please convert with `XeLaTeX` first? You may need to add `\usepackge{fontspec}`:
 
<img width="480" alt="Screenshot 2020-05-15 at 11 11 55 AM" src="https://user-images.githubusercontent.com/1103696/82007473-e50b2980-969c-11ea-947c-7f91f7a00371.png">

**Comment by liantze** [comment]
I've just pushed an update; could you try compiling with pdflatex using `altacv.cls` v1.3.1?

**Comment by gcakir** [comment]
@liantze It works now, with pdflatex as well. Thank you very much.

**Comment by liantze** [comment]
Great, thanks for the report!
