### ISSUE TITLE
Could you add support for gitlab just like there is for github?

### ISSUE THREAD

**Issue by tristan957** [liantze/AltaCV#5]
Add gitlab support

**Comment by tristan957** [comment]
Nevermind. Found out about fontawesome. Thank you

**Comment by tristan957** [comment]
\newcommand{\gitlab}[1]{\printinfo{\faGitlab}{#1}}

**Comment by liantze** [comment]
You don't actually need to define a specific command either if you just need it once, i.e. just put `\printinfo{\faGitlab}{http://gitlab.com/your_id}` in `\personal_info{}`.
