### ISSUE TITLE
Display two Images at the top right hand corner

### ISSUE THREAD

**Issue by aztec3** [liantze/AltaCV#51]
Hello, 
         I love your AltaCV template. Its clear and concise. I have managed to display an image at the top right corner. However, when I try to display two images, I run into errors. It won't compile.

Is it necessary for the two images to have the same extension? 

Thanks a lot and much appreciated.
Cheers!

**Comment by liantze** [comment]
No, they don't have to be. Things _should_ work with something like `\photoR{2.5cm}{photo.jpg,photo2.png}`.

**Comment by aztec3** [comment]
I did as you suggested, unfortunately it doesn't work for me. I'm using the pdflatex-bitex-pdflatex sequence and I get an error saying '! Undefined control sequence.'
i tried with extensions, without extensions and with same file types as well. I'm able to get a single image though. 
Later on I reduced the size of the image as well, I still get the same error as above.

I really really appreciate how quickly you have responded to my question. God Speed and safe travels, Friend.

**Comment by liantze** [comment]
Are you using the latest version of altacv.cls?

**Comment by aztec3** [comment]
I'm using the older version because it works, the newest version gives me an error,
       Unknown option 'fixed' for package fontawesome5
I have also searched in the previously solved posts(issues) and that made me more confused. 
Will keep trying though. 
Thanks

**Comment by liantze** [comment]
Older versions of `altacv.cls` does not support multiple photos: `\photoL`, `\photoR` are new commands.

Upgrade your `fontawesome5` package with MikTeX Package Manager or TeX Live Manager, depending on whichever LaTeX distribution you're using.

**Comment by aztec3** [comment]
Thanks a lot, will update it and compile after. Cheers.
