### ISSUE TITLE
Personal details on Top right

### ISSUE THREAD

**Issue by VinodKumar9576** [liantze/AltaCV#53]
Hi @liantze ,

Can you please help me on how can i achieve the below format?
Personal details to show on the top right corner of cv just like below highlighted.
Right now i'm able to add personal details as footnotes. But what i want is to have below format of personal details. Don't mind about the picture as i don't need it in resume. I just need to have personal details on the top right.

![image](https://user-images.githubusercontent.com/23068132/86046096-41b67e00-ba6a-11ea-8f4f-c553eec6b732.png)

**Comment by VinodKumar9576** [comment]
if possible can you please provide me `makecvheader` code that should have below things
* Name
* tagline
* Brief summary
* On the right side to have personal details
* No photo needed in the header

I'd really appreciate your help on this.

**Comment by VinodKumar9576** [comment]
@akreuzer @jackdreinhardt @stefanogermano 
Can any of you help me on this please.
I would be grateful for your kind help.

**Comment by liantze** [comment]
Currently I don't really have plans to drastically introduce layout changes similar to this, sorry. It may be best to search for other CV templates that already have a similar layout to this.
