### ISSUE TITLE
Colors under dvipsnames are different when using AltaCV

### ISSUE THREAD

**Issue by rajodecastro** [liantze/AltaCV#54]
Colors seem to shift when loading the **altacv** document type.

Using **article** document type:
```
\documentclass{article}
\usepackage[dvipsnames]{xcolor}
\begin{document}
Using article:
\large
\fcolorbox{Aquamarine}{Aquamarine}{Aquamarine}
\fcolorbox{Emerald}{Emerald}{Emerald}
\fcolorbox{Goldenrod}{Goldenrod}{Goldenrod}
\end{document}
```
[article-color.pdf](https://github.com/liantze/AltaCV/files/5005278/article-color.pdf)

Using **altacv** document type:
```
\PassOptionsToPackage{dvipsnames}{xcolor}
\documentclass{altacv}
\begin{document}
Using AltaCV:
\fcolorbox{Aquamarine}{Aquamarine}{Aquamarine}
\fcolorbox{Emerald}{Emerald}{Emerald}
\fcolorbox{Goldenrod}{Goldenrod}{Goldenrod}
\end{document}
```
[altacv-color.pdf](https://github.com/liantze/AltaCV/files/5005282/altacv-color.pdf)

**Comment by liantze** [comment]
`altacv.cls` now loads `\RequirePackage[a-1b]{pdfx}`, which uses an RGB colour profile; but `dvipsnames` colours are CMYK. Related: https://tex.stackexchange.com/questions/464079/pdfx-cmyk-color-profile-in-pdf-a but it doesn't seem to work for me.

(I should remove the example `\PassOptionsToPackage` in `sample.tex`)
