### ISSUE TITLE
Software/Design Projects command

### ISSUE THREAD

**Issue by Tepexic** [liantze/AltaCV#55]
I've updated my CV recently, and I was wondering if you'd be interested on adding something like these two new commands I've put together for my "Projects" section

```
\newcommand{\cvgithubproject}[3]{%
  {\large\color{emphasis}#1\par}
  \smallskip
  {\small\makebox[\linewidth][l]{\faGithub \hspace{0.5em}#2}\par
  \ifthenelse{\equal{#3}{}}{}{{\smallskip\small\makebox[\linewidth][l]{\faLaptop \hspace{0.5em}#3}}\par}}%
  \medskip
}

\newcommand{\cvcodepenproject}[2]{%
  {\large\color{emphasis}#1\par}
  \smallskip
  {\small\makebox[\linewidth][l]{\faCodepen \hspace{0.5em}#2}\par}
  \medskip
}
```

This is how they look like:
![Capture](https://user-images.githubusercontent.com/5529431/90019775-7ece7c80-dc74-11ea-8b4e-6ee34afa5741.PNG)

Thanks

**Comment by liantze** [comment]
Covered by https://github.com/liantze/AltaCV#new-information-fields and https://github.com/liantze/AltaCV/issues/25.
