### ISSUE TITLE
Putting different symbol in the "Most Proud of Section"

### ISSUE THREAD

**Issue by Maliha-huma** [liantze/AltaCV#6]
Hello,
How to put a symbol different than Heartbeat, Flatline, Female or Trophy in the \cvachievement{\.....} (Most Proud of) section? 

Any help is appreciated!
Huma

**Comment by SudipSinha** [comment]
Replace the `\faHeartbeat` etc with any of the `\fa<Symbol>`. You can find a list of the symbols in the [fontawesome package manual](ftp://ftp.dante.de/tex-archive/fonts/fontawesome/doc/fontawesome.pdf).

**Comment by liantze** [comment]
As @SudipSinha points out this is an easy fix in the `.tex` file (sorry I missed the OP's message; it was a blur two weeks ago argh); therefore closing.
