### ISSUE TITLE
Create a github actions that compile the pdf

### ISSUE THREAD

**Issue by badetitou** [liantze/AltaCV#61]
Hello,

I love your template! great job!

I'm trying to create a GitHub action that compile this latex file without any success...
If you have any knowledge of GitHub actions, would you consider adding the yml file in the repository?

**Comment by liantze** [comment]
That's an interesting idea, but I think that's probably out of my scope. If other users have any idea about this, feel free to fork it.

**Comment by liantze** [comment]
see also #102
