### ISSUE TITLE
href does not work

### ISSUE THREAD

**Issue by naarkhoo** [liantze/AltaCV#65]
It seems href does not work even if I do like \href{http://www.google.com}{Google} - neither in the text nor in the cvevent title. Am perhaps I missing something ? 

I am using the template provided on overleaf. Thank you again for making this package

**Comment by naarkhoo** [comment]
I had to use

```
\usepackage[hidelinks]{hyperref}
...
\href{www.google.com}{Google}
```

**Comment by liantze** [comment]
See README re `withhyper` option.
