### ISSUE TITLE
\cvtag placed out of page \geometrie

### ISSUE THREAD

**Issue by shahram7** [liantze/AltaCV#67]
Hi everyone,
i don't know how can i fix it. 
![image](https://user-images.githubusercontent.com/34509793/105368077-70ac6100-5c01-11eb-9905-c6a4fa5733ee.png)

i know i can put "\\" after "\cvtag{MS Excel}"
but i thought there should be a reasonable solution!

thank you all

**Comment by liantze** [comment]
Adding a space or a hard line break `\\` would be the easiest solution...
