### ISSUE TITLE
Guidance on photo manipulation (i.e. cropping and panning)

### ISSUE THREAD

**Issue by kubark42** [liantze/AltaCV#69]
The photo placement is very nicely done, but it's cumbersome to fit an actual image to the CV. Could we have guidance on how to adjust the  pan, zoom, and crop parameters?

**Comment by liantze** [comment]
There is a `normalphoto` class option that doesn't apply the circular cropping: the image would simply be inserted like a `\includegraphics`.

```
%% Use the "normalphoto" option if you want a normal photo instead of cropped to a circle
\documentclass[10pt,a4paper,ragged2e,withhyper,normalphoto]{altacv}
\photoR{2.8cm}{example-image}
```

<img width="460" alt="Screenshot 2021-05-12 at 10 51 12 AM" src="https://user-images.githubusercontent.com/1103696/117911217-fae31700-b30f-11eb-990f-d74a11b45207.png">
