### ISSUE TITLE
personalinfo spacing/alignment

### ISSUE THREAD

**Issue by step21** [liantze/AltaCV#73]
I added `\orcid{}` and now in the front, I have e-mail address and orcid (in two lines), but they do not start at the same position, which looks off. See below:
![grafik](https://user-images.githubusercontent.com/46968/108270182-641f1800-716f-11eb-851d-6ef46f7fc608.png)

Is it supposed to be like this or something I did?

**Comment by liantze** [comment]
Thanks; that sample code seems to work fine for me though. Are you using the latest (or, relatively new) version of altacv.cls?

**Comment by step21** [comment]
I think it says version 1.3.2 from 17th May 2020. Is that recent enough?

**Comment by liantze** [comment]
Perhaps try using the latest one v1.5; now you don't need the "academicons" option and can compile using pdflatex to use `\orcid{...}`.

**Comment by step21** [comment]
Thanks, that fixed it. Sorry for taking the time, I should have checked for an updated version.
