### ISSUE TITLE
cvevent date and location overlap

### ISSUE THREAD

**Issue by Andrew-Fahmy** [liantze/AltaCV#82]
First off I would like to thank you for the amazing template.

The only issue I have ran into so far was with a slight overlap in the date and location under a cvevent when using a two column layout. I think this is due to both text fields [taking half of the width](https://github.com/liantze/AltaCV/blob/6b54c51acbac8dc05ed1086071a22ae43960efc3/altacv.cls#L293). I don't know a lot about latex, but one thought that I had was to allow a way to change this ratio before creating a cvevent.

Here is a sample to reproduce what I mean:
```latex
\documentclass[12pt, letterpaper]{altacv}

\usepackage{paracol}

\usepackage[default]{lato}

\begin{document}
    \name{}
    \tagline{}

    \personalinfo{
    }

    \begin{fullwidth}
        \makecvheader
    \end{fullwidth}

    \columnratio{0.55}
    \begin{paracol}{2}

        \switchcolumn
        \cvsection{Education}
        \cvevent{Bachelor of Science in Something}{Some University}{August 2015 -- June 2018}{Some, Town}
        \begin{itemize}
            \item some point
        \end{itemize}

    \end{paracol}
\end{document}
```
![image](https://user-images.githubusercontent.com/19921865/123299336-09ac1480-d4df-11eb-9d28-9bed771188bf.png)

**Comment by liantze** [comment]
It's a bit klunky; but you can "patch" the width for the date and the location using `\patchcmd`:

```latex
% Replace the first occurence 0.5\linewidth with 0.6\linewidth
\patchcmd{\cvevent}{0.5\linewidth}{0.6\linewidth}{}{}
% Replace the second occurence 0.5\linewidth with 0.4\linewidth
\patchcmd{\cvevent}{0.5\linewidth}{0.4\linewidth}{}{}
```

<img width="700" alt="Screenshot 2021-06-25 at 3 48 18 PM" src="https://user-images.githubusercontent.com/1103696/123389737-c4fea700-d5cc-11eb-8f40-8b05fcc9bb4c.png">

**Comment by Andrew-Fahmy** [comment]
That works It is kind of a niche thing to change so I don't think it's  a big deal if it's clunky.  I had never heard about patchcmd before so thank you for this fix!
