### ISSUE TITLE
Text overlap in CV event with long text and limited width

### ISSUE THREAD

**Issue by AlbertoFabbri93** [liantze/AltaCV#89]
![LaTeX text overlap](https://user-images.githubusercontent.com/51910894/141119758-f04bd298-1abf-499f-b466-4d888d99f795.jpg)
Would it be possible to make the city/country area automatically go on a new line if the space is insufficient? If doing so automatically is not possible, how can I force it manually?

**Comment by liantze** [comment]
If you need this behavior for all your `\cvevent`, you can add this before `\begin{document}`:
```latex
\patchcmd{\cvevent}{\ifstrequal{#4}}{\par\ifstrequal{#4}}{}{}
```

But if you just want this for a particular `\cvevent` or a section, then you can use the `\patchcmd` just before the first `\cvevent` with `{...}` around, to limit the scope of change:

```latex
{
\patchcmd{\cvevent}{\ifstrequal{#4}}{\par\ifstrequal{#4}}{}{}
\cvevent{Activity}{Institution}{September...}{City...}
\begin{itemize}...\end{itemize}

\cvevent{...} % any other \cvevents that need this treatment
}
```

**Comment by AlbertoFabbri93** [comment]
Perfect! Thank you!
