### ISSUE TITLE
Missing \begin{document}

### ISSUE THREAD

**Issue by khuatu** [liantze/AltaCV#92]
Hi there,
I downloaded template.
After running the mmayer.tex I got the error log:
![image](https://user-images.githubusercontent.com/96387630/146684101-2efbd776-929a-4779-b058-988de6d85725.png)
I used LuaLatex.
Can anyone tell me what I did wrong?

**Comment by liantze** [comment]
Compiling with LuaLaTeX works fine for me. Perhaps try updating all packages in your MikTeX/TeX Live installation?

**Comment by khuatu** [comment]
Oh yes, I just needed to update all packages.
Thank you very much!
