### ISSUE TITLE
Publish on CTAN?

### ISSUE THREAD

**Issue by kir0ul** [liantze/AltaCV#94]
Hi there,

I just found out about this class which looks really nice!

I was wondering if you would consider publishing it on [CTAN](https://ctan.org/) so that it'll become available on TeX distributions like TeX Live?

Some references in case it's useful:
1. https://ctan.org/upload
2. https://ctan.org/help/upload-pkg

**Comment by liantze** [comment]
Thanks for the suggestion; but no current plans to publish this on CTAN. :-)
