### ISSUE TITLE
Overleaf AltaCV / Sidebar not show on page 2

### ISSUE THREAD

**Issue by LesliekWood** [liantze/AltaCV#95]
Hello

is there anyway to not show the sidebar on page 2 and let the section go across the entire page?
I still want the sidebar to show on page 1.

Thanks
Leslie Wood

**Comment by liantze** [comment]
Look for the `\end{paracol}` in your .tex file, then move it to the end of your first page contents (including sidebar). Add `\clearpage` after `\end{paracol}` to start a new page if necessary.

**Comment by LesliekWood** [comment]
Thanks for the help, there isn't any \end{paracol} but I did solve it by using

% Make Section go full width of the page
\newenvironment{fullwidth}{%
  \begin{adjustwidth}{}{\dimexpr-\marginparwidth-\marginparsep\relax}}
  {\end{adjustwidth}}

\begin{fullwidth} 

\end{fullwidth}
