### ISSUE TITLE
How to use option normalphoto?

### ISSUE THREAD

**Issue by Jaisme** [liantze/AltaCV#99]
Hello, thanks for this nice cv template. I'm quiet new to LaTeX and I would like to use the square photo. But unfortunately it didn't work with e.g.  \photoR**{normalphoto}**{3.0cm}{photo} or  \photoR**[normalphoto]**{3.0cm}{photo}. How can I set the photo to square?

**Comment by LucasForster** [comment]
Hi, that seems to be an option for the documentclass, not the photo command itself, try:
`\documentclass[12pt,a4paper,normalphoto]{altacv}`

**Comment by Jaisme** [comment]
That works! Thanks a lot :D
